# -*- coding: utf-8 -*-
"""1001:A-B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Iv8DVc9Zmf9oTUybmvnbWTY74fgkZ22x
"""

a, b = map(int, input().split())
result = a-b

print(result)
